### PR TITLE
fixed invalid email

### PR DESCRIPTION
**Pull request by Jenniebn**
Sorry forgot about the screen shot
Screenshot 2024-02-20 at 21 51 08

### CODE REVIEW

**Review by jenniferlopez17 — COMMENTED** [review]
You're not passing the mutation tests. In frontend/src/main/components/HelpRequest/HelpRequestForm.js, you could try to replace lines 24 and 26 with "// Stryker disable next-line Regex" instead and get rid of line 28 which says "// Stryker disable next-line all"

**Review by andyjin1 — COMMENTED** [review]
Code looks good could you provide a screenshot of invalid email or dokku deployment link?

**Review by welaalice — APPROVED** [review]
LGTM and passing mutation test now

**Review by andyjin1 — APPROVED** [review]
Looks good!

**Pull request merged**
